# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        K-anonymity: 2
        mondrian: 2
        differential privacy: 2
        
        data linkage: 1
        database: 1
        
        anonymization: 1
        anonymous: 1
        privacy: 2
        
        mining: 1
        machine learning: 1
        deep learning: 1

# 通知の閾値
score_threshold: 5
